# Generated by Django 2.0.6 on 2018-10-23 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adj_close',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adj_open', models.FloatField(max_length=20)),
                ('moving_avg', models.FloatField(max_length=20)),
                ('adj_high', models.FloatField(max_length=20)),
                ('adj_low', models.FloatField(max_length=20)),
                ('hl_pct', models.FloatField(max_length=20)),
                ('pct_change', models.FloatField(max_length=20)),
                ('adj_vol', models.FloatField(max_length=20)),
                ('avg', models.FloatField(max_length=20)),
                ('runtime', models.FloatField(max_length=20)),
            ],
        ),
    ]
